name: FLUTTERPROJECT
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  unicons: ^2.1.1
  get_storage: 2.1.1
  get: 4.6.6
  image_picker: ^1.0.4
  path_provider: ^2.0.8
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_svg: ^2.0.8
  font_awesome_flutter: ^10.0.1
  webview_flutter: ^4.4.1
  geolocator: ^9.0.2
  fancy_shimmer_image: ^2.0.3
  dio: ^5.3.3
  http: ^1.0.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.4
  appwrite: ^9.0.0
  shared_preferences: ^2.2.2
  flutter: 
    sdk: flutter
  provider: ^6.1.1
  

dev_dependencies: 
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  mockito: ^5.4.3

flutter: 
  assets: 
    - images/
  uses-material-design: true

